### ISSUE TITLE
Cannot search for artists

### ISSUE THREAD

**Issue by kevinharvey** [kevinharvey/jmad#10]
Attempting to search for an artist, either one that already exists or not, returns a 500 ISE. Traceback from `jmad.log`:

```
[23/Jan/2016 02:27:58] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/utils/__init__.py", line 420, in __call__
    return self.__value__
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/transport/virtual/__init__.py", line 789, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/connection.py", line 436, in _ensured
    return fun(*args, **kwargs)
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/messaging.py", line 177, in _publish
    channel = self.channel
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/messaging.py", line 194, in _get_channel
    channel = self._channel = channel()
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/utils/__init__.py", line 422, in __call__
    value = self.__value__ = self.__contract__()
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/messaging.py", line 209, in <lambda>
    channel = ChannelPromise(lambda: connection.default_channel)
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/connection.py", line 756, in default_channel
    self.connection
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/transport/virtual/__init__.py", line 809, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/transport/virtual/__init__.py", line 791, in create_channel
    channel = self.Channel(connection)
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/transport/redis.py", line 443, in __init__
    self.client.info()
  File "/webapps/jmad/lib/python3.4/site-packages/redis/client.py", line 657, in info
    return self.execute_command('INFO')
  File "/webapps/jmad/lib/python3.4/site-packages/redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/webapps/jmad/lib/python3.4/site-packages/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/webapps/jmad/lib/python3.4/site-packages/redis/connection.py", line 574, in read_response
    raise response
redis.exceptions.ResponseError: NOAUTH Authentication required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/transport/virtual/__init__.py", line 789, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/webapps/jmad/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/webapps/jmad/jmad-project/jmad/solos/views.py", line 26, in index
    get_artist_tracks_from_musicbrainz.delay(artist=artist_kwarg)
  File "/webapps/jmad/lib/python3.4/site-packages/celery/app/task.py", line 453, in delay
    return self.apply_async(args, kwargs)
  File "/webapps/jmad/lib/python3.4/site-packages/celery/app/task.py", line 559, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/webapps/jmad/lib/python3.4/site-packages/celery/app/base.py", line 353, in send_task
    reply_to=reply_to or self.oid, **options
  File "/webapps/jmad/lib/python3.4/site-packages/celery/app/amqp.py", line 305, in publish_task
    **kwargs
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/connection.py", line 457, in _ensured
    interval_max)
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/connection.py", line 369, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/utils/__init__.py", line 243, in retry_over_time
    return fun(*args, **kwargs)
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/connection.py", line 237, in connect
    return self.connection
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/connection.py", line 741, in connection
    self._connection = self._establish_connection()
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/connection.py", line 696, in _establish_connection
    conn = self.transport.establish_connection()
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/transport/virtual/__init__.py", line 809, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/transport/virtual/__init__.py", line 791, in create_channel
    channel = self.Channel(connection)
  File "/webapps/jmad/lib/python3.4/site-packages/kombu/transport/redis.py", line 443, in __init__
    self.client.info()
  File "/webapps/jmad/lib/python3.4/site-packages/redis/client.py", line 657, in info
    return self.execute_command('INFO')
  File "/webapps/jmad/lib/python3.4/site-packages/redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/webapps/jmad/lib/python3.4/site-packages/redis/client.py", line 577, in parse_response
    response = connection.read_response()
  File "/webapps/jmad/lib/python3.4/site-packages/redis/connection.py", line 574, in read_response
    raise response
redis.exceptions.ResponseError: NOAUTH Authentication required.
```

**Comment by kevinharvey** [comment]
Restarting the server fixes the problem.
